# Generated by Django 3.2.5 on 2021-07-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTransaction',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('mb_fintxns', models.PositiveBigIntegerField()),
                ('mb_nonfintxns', models.PositiveBigIntegerField()),
                ('mb_totaltxn', models.PositiveBigIntegerField()),
                ('mb_td', models.PositiveBigIntegerField()),
                ('mb_td_percent', models.FloatField()),
                ('mb_bd', models.PositiveBigIntegerField()),
                ('upi_fintxns', models.PositiveBigIntegerField()),
                ('upi_nonfintxns', models.PositiveBigIntegerField()),
                ('upi_totaltxn', models.PositiveBigIntegerField()),
                ('upi_td', models.PositiveBigIntegerField()),
                ('upi_td_percent', models.FloatField()),
                ('upi_bd', models.PositiveBigIntegerField()),
                ('imps_totaltxn', models.PositiveBigIntegerField()),
                ('imps_td', models.PositiveBigIntegerField()),
                ('imps_td_percent', models.FloatField()),
                ('imps_bd', models.PositiveBigIntegerField()),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
