# Generated by Django 3.2.5 on 2021-08-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncrementalUser',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('inc_upiUsers', models.PositiveBigIntegerField()),
                ('inc_mbUsers', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TotalUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_Upi_Users', models.PositiveBigIntegerField()),
                ('total_Mb_Users', models.PositiveBigIntegerField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
    ]
