# Generated by Django 3.2.5 on 2021-08-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_incrementaluser_totalusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='XLSheets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xlsheet', models.FileField(upload_to='transaction')),
            ],
        ),
    ]
