# Generated by Django 3.2.5 on 2021-08-06 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_xlsheets'),
    ]

    operations = [
        migrations.DeleteModel(
            name='XLSheets',
        ),
    ]
