# Generated by Django 3.2.5 on 2021-08-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_delete_xlsheets'),
    ]

    operations = [
        migrations.CreateModel(
            name='XLSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xl', models.FileField(upload_to='transaction')),
            ],
        ),
    ]
