# Generated by Django 3.2.5 on 2021-08-08 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_xlsheet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='XLSheet',
        ),
    ]
