# Generated by Django 3.2.5 on 2021-07-25 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('constants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('fin_txn', models.PositiveBigIntegerField()),
                ('fin_rate', models.FloatField()),
                ('nonfin_txn', models.PositiveBigIntegerField()),
                ('nonfin_rate', models.FloatField()),
                ('base_amt', models.PositiveBigIntegerField()),
                ('gst_percent', models.FloatField()),
                ('gst_amt', models.PositiveBigIntegerField()),
                ('penalty', models.PositiveBigIntegerField()),
                ('final_payment', models.PositiveBigIntegerField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constants.module')),
            ],
        ),
    ]
