# Generated by Django 3.2.5 on 2021-07-31 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_auto_20210726_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditure',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to='invoices/%Y/%m/%d'),
        ),
    ]
