# Generated by Django 3.2.5 on 2021-08-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20210802_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadeddocument',
            name='document',
            field=models.FileField(upload_to='projects/invoices/%Y/%m/%d'),
        ),
    ]
