# Generated by Django 3.2.5 on 2021-07-31 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constants', '0002_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priority',
            name='id',
        ),
        migrations.AlterField(
            model_name='priority',
            name='code',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
    ]
